
'use strict';

export default {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_INIT: 'THEME_INIT',
    POPULAR_REFRESH: 'POPULAR_REFRESH',
    POPULAR_UPLOAD_FAIL: 'POPULAR_UPLOAD_FAIL',
    POPULAR_UPLOAD_SUCCESS: 'POPULAR_UPLOAD_SUCCESS',
    POPULAR_REFRESH_MORE_SUCCESS: 'POPULAR_REFRESH_MORE_SUCCESS',
    POPULAR_REFRESH_MORE_FAIL: 'POPULAR_REFRESH_MORE_FAIL'
}
